apiVersion: v1
kind: ConfigMap
metadata:
  name: mdai-collector-config
  namespace: mdai
data:
  collector.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      k8s_events:
        namespaces:
          - mdai
    
    processors:
      batch:
        send_batch_size: 1000
        send_batch_max_size: 10000
        timeout: 13s
      filter/severity:
        error_mode: ignore
        logs:
          log_record:
            - 'severity_number < SEVERITY_NUMBER_WARN'
    
    exporters:
      debug: {}
      debug/verbose:
        verbosity: detailed
    #  awss3/audit: {}
    #  awss3/collector: {}
    #  awss3/mdai_components: {}
    #  awss3/otherlogs: {}
    #  file/audit: {}
    #  file/collector: {}
    #  file/mdai_components: {}
    
    connectors:
      routing/logstream:
        default_pipelines: [logs/other]
        table:
          - context: log
            condition: attributes["mdai-logstream"] == "audit"
            pipelines: [logs/s3audit, logs/bufferaudit]
          - context: log
            condition: attributes["mdai-logstream"] == "collector"
            pipelines: [logs/s3collector, logs/buffercollector]
          - context: log
            condition: attributes["mdai-logstream"] == "hub"
            pipelines: [logs/s3hub, logs/bufferhub]
    
    extensions:
      cgroupruntime:
        gomaxprocs:
          enabled: true
        gomemlimit:
          enabled: true
    
    service:
      pipelines:
        logs/k8s_events:
          receivers: [k8s_events]
          processors: []
          exporters: [debug/verbose]
        metrics:
          receivers: [otlp]
          processors: []
          exporters: [debug]
        logs/input:
          receivers: [otlp]
          processors: [] #filter/severity] #, batch]
          exporters: [routing/logstream]
        logs/bufferaudit:
          receivers: [routing/logstream]
          processors: [] #batch]
          exporters: [debug]
        #      exporters: [file/audit]
        logs/s3audit:
          receivers: [routing/logstream]
          processors: [filter/severity] #, batch]
          exporters: [debug]
        #      exporters: [awss3/audit]
        logs/bufferhub:
          receivers: [routing/logstream]
          processors: [] #batch]
          exporters: [debug]
        #      exporters: [file/mdai_components]
        logs/s3hub:
          receivers: [routing/logstream]
          processors: [filter/severity] #, batch]
          exporters: [debug]
        #      exporters: [awss3/mdai_components]
        logs/buffercollector:
          receivers: [routing/logstream]
          processors: [] #batch]
          exporters: [debug]
        #      exporters: [file/collector]
        logs/s3collector:
          receivers: [routing/logstream]
          processors: [filter/severity] #, batch]
          exporters: [debug]
        #      exporters: [awss3/collector]
        logs/other:
          receivers: [routing/logstream]
          processors: [] #batch]
          exporters: [debug]
    #      exporters: [awss3/otherlogs]