apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mdai
  name: mdai-collector
  labels:
    app: mdai-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mdai-collector
  template:
    metadata:
      labels:
        app: mdai-collector
        app.kubernetes.io/component: mdai-collector
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8899"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: mdai-collector
      containers:
        - name: mdai-collector
          image: mdai-collector:0.1.0
          ports:
            - containerPort: 8888
              name: otelcol-metrics
            - containerPort: 8899
              name: mdai-metrics
            - containerPort: 4317
              name: otlp-grpc
            - containerPort: 4318
              name: otlp-http
          volumeMounts:
            - name: config-volume
              mountPath: /conf/collector.yaml
              subPath: collector.yaml
          command:
            - "/collector"
            - "--config=/conf/collector.yaml"
      volumes:
        - name: config-volume
          configMap:
            name: mdai-collector-config