apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdai-telemetry-pv
  namespace: mdai
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/shared/mdai/logs
    type: DirectoryOrCreate