apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdai-telemetry-pvc
  namespace: mdai
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi