apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mdai-telemetry-pvc
  namespace: mdai
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi