apiVersion: v1
kind: Service
metadata:
  name: mdai-collector-service
  namespace: mdai
  labels:
    app: mdai-collector
spec:
  selector:
    app: mdai-collector
  ports:
    - port: 4317
      targetPort: otlp-grpc
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: otlp-http
      protocol: TCP
      name: otlp-http
    - port: 8888
      targetPort: otelcol-metrics
      protocol: TCP
      name: otelcol-metrics
  type: ClusterIP
