name: Docker push observer-collector for new tag

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

jobs:
  docker-push:
    uses: DecisiveAI/ci/.github/workflows/docker-push-to-ecr.yml@rlaw/ENG-689-docker-and-helms
    with:
      image_name_suffix: observer-collector
    secrets:
      SLACK_NOTIFY_URL: ${{ secrets.SLACK_NOTIFY_URL }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}